/* Zentrale Website-Bausteine – Änderungen hier gelten auf allen eingebundenen Seiten. */
const SITE={sponsors:[
{name:'Allianz Suisse',type:'haupt',logo:'assets/logos/allianz.png',url:'https://www.maeder-allianz.ch/'},
{name:'Mathiblitz',type:'haupt',logo:'assets/logos/mathiblitz.png',url:'https://www.mathiblitz.ch/'},
{name:'Dogger',type:'gold',logo:'assets/logos/Dogger.jpg',url:'https://www.dogger.ch/'},
{name:'IGKO',type:'gold',logo:'assets/logos/Logo IGKO.jpg',url:'https://igko.ch/'},
{name:'Happy Dog',type:'gold',logo:'assets/logos/HappyDog.png',url:'https://www.luginbuehl-tiernahrung.ch/'},
{name:'Pfotenhoch4',type:'gold',logo:'assets/logos/Pfotenhoch4.jpg',url:'https://pfotenhoch4.ch/'},
{name:'Mathiblitz',type:'gold',logo:'assets/logos/mathiblitz.png',url:'https://www.mathiblitz.ch/'}
]};
function siteRoot(){const script=[...document.scripts].find(s=>s.src&&s.src.includes('components.js'));if(!script)return '';const url=new URL(script.src,window.location.href);return url.href.slice(0,url.href.lastIndexOf('/')+1)}
function siteUrl(path=''){return siteRoot()+path}
const PRETTY={'index.html':'','club.html':'club/','training.html':'training/','agenda.html':'agenda/','news.html':'news/','sponsoren.html':'sponsoren/','mitgliedschaft.html':'mitgliedschaft/','kontakt.html':'kontakt/','100-jahre.html':'100-jahre/','links.html':'links/','news/herbstpruefung-2025.html':'news/herbstpruefung-2025/'};
const LEGACY_ASSETS={'Boxerkopf-Bern.jpg.png':'assets/logos/boxerkopf-bern.png','AZ_Logo_positive_RGB.png':'assets/logos/allianz.png','Mathi Blitz.png':'assets/logos/mathiblitz.png','logo-og-bern.png':'assets/logos/logo-og-bern.png','SBC_1906.png':'assets/logos/sbc.png','Logo-SKG_1000x240px_Weiss (1).png':'assets/logos/skg.png','boxer-duo.jpg':'assets/images/boxer-duo.jpg','boxer-wald.jpg':'assets/images/boxer-wald.jpg','Caroline Baumann.jpg':'assets/images/vorstand/caroline-baumann.jpg','Fabienne Burgener.jpg':'assets/images/vorstand/fabienne-burgener.jpg','Martina Beyeler.jpeg':'assets/images/vorstand/martina-beyeler.jpeg','Martina Marti.jpg':'assets/images/vorstand/martina-marti.jpg','Michael Bracher.jpg':'assets/images/vorstand/michael-bracher.jpg','Nina Clavey.jpg':'assets/images/vorstand/nina-clavey.jpg','Sandra Gadient.jpg':'assets/images/vorstand/sandra-gadient.jpg','Simon Vonrüti.jpeg':'assets/images/vorstand/simon-vonrueti.jpeg','Simon Vonrüti.jpeg':'assets/images/vorstand/simon-vonrueti.jpeg','Ueli Burgener.jpg':'assets/images/vorstand/ueli-burgener.jpg','Beitrittsgesuch 2026 (1).pdf':'assets/documents/beitrittsgesuch-2026.pdf','SBC Mitgliederbeiträge ab 01.01.2025[38].pdf':'assets/documents/sbc-mitgliederbeitraege-2025.pdf','SBC Statuten 2020 (1).pdf':'assets/documents/sbc-statuten-2020.pdf'};
function migrateLegacyAssets(){const variants=[];Object.entries(LEGACY_ASSETS).forEach(([o,n])=>variants.push([o,n],[encodeURI(o),n]));document.querySelectorAll('img[src],a[href],source[src]').forEach(el=>{const attr=el.hasAttribute('href')?'href':'src',value=el.getAttribute(attr)||'';if(!value||/^(https?:|mailto:|tel:|#)/i.test(value))return;for(const [o,n] of variants){let d=value;try{d=decodeURI(value)}catch{}if(value===o||d===o){el.setAttribute(attr,siteUrl(n));break}}});document.querySelectorAll('style').forEach(style=>{let css=style.textContent,changed=false;Object.entries(LEGACY_ASSETS).forEach(([o,n])=>{const r=siteUrl(n);[`url('${o}')`,`url(\"${o}\")`,`url(${o})`].forEach(p=>{if(css.includes(p)){css=css.split(p).join(`url('${r}')`);changed=true}})});if(changed)style.textContent=css})}
function prettyLinks(){document.querySelectorAll('a[href]').forEach(a=>{const raw=a.getAttribute('href')||'';if(!raw||/^(https?:|mailto:|tel:|#)/i.test(raw))return;let clean=raw.replace(/^\.\.\//,'').replace(/^\.\//,'');for(const [oldPath,newPath] of Object.entries(PRETTY)){if(clean===oldPath){a.setAttribute('href',siteUrl(newPath));return}}})}
function sponsorHeaderRow(type,label){const sponsors=SITE.sponsors.filter(s=>s.type===type);if(!sponsors.length)return '';return `<div class="top-sponsor-row ${type}"><span class="top-sponsor-label">${label}</span><div class="top-sponsor-logos">${sponsors.map(s=>`<a href="${s.url}" target="_blank" rel="noopener" title="${s.name}"><img src="${siteUrl(s.logo)}" alt="${s.name}"></a>`).join('')}</div></div>`}
function mainSponsorStrip(){return `<div class="top-sponsor-strip"><div class="site-wrap top-sponsor-stack">${sponsorHeaderRow('haupt','Hauptsponsoren')}${sponsorHeaderRow('gold','Gold-Sponsoren · 100 Jahre')}</div></div>`}
function siteHeader(){return `<header class="site-nav"><div class="site-navin"><a class="site-brand" href="${siteUrl('')}"><img src="${siteUrl('assets/logos/boxerkopf-bern.png')}" alt="Schweizerischer Boxer-Club Ortsgruppe Bern 1926"></a><button class="site-menu-btn" aria-label="Menü öffnen" onclick="document.querySelector('.site-menu').classList.toggle('open')">☰</button><nav class="site-menu"><span class="site-dropdown"><button class="site-dropdown-btn" type="button">Club <span aria-hidden="true">▾</span></button><span class="site-dropdown-menu"><a href="${siteUrl('club/')}">Unsere Ortsgruppe</a><a href="${siteUrl('sponsoren/')}">Sponsoren & Partner</a><a href="${siteUrl('links/')}">Links</a></span></span><a href="${siteUrl('training/')}">Training</a><a href="${siteUrl('agenda/')}">Agenda</a><a href="${siteUrl('news/')}">News</a><span class="site-dropdown"><button class="site-dropdown-btn" type="button">Geschichte <span aria-hidden="true">▾</span></button><span class="site-dropdown-menu"><a href="${siteUrl('100-jahre/')}">100 Jahre OG Bern</a></span></span><a href="${siteUrl('mitgliedschaft/')}">Mitgliedschaft</a><a href="${siteUrl('kontakt/')}">Kontakt</a></nav></div></header>`}
function sponsorLogo(s){return `<a class="sponsor-logo" href="${s.url}" target="_blank" rel="noopener" title="${s.name}"><img src="${siteUrl(s.logo)}" alt="${s.name}"><span>${s.name}</span></a>`}
function sponsorBlock(){const others=SITE.sponsors.filter(s=>s.type!=='haupt'&&s.type!=='gold');if(!others.length)return '';const logos=others.map(s=>sponsorLogo(s)).join('');return `<section class="site-sponsors"><div class="sponsor-ticker-block"><div class="sponsor-label">Unsere Partner & Sponsoren</div><div class="sponsor-ticker"><div class="sponsor-track">${logos}${logos}</div></div></div></section>`}
function enhanceSponsorPage(){const gold=document.querySelector('.tier.gold');if(!gold)return;const logos={'Pfotenhoch4.ch':{logo:'assets/logos/Pfotenhoch4.jpg',url:'https://pfotenhoch4.ch/',alt:'Pfotenhoch4'},'Mathiblitz Gümligen':{logo:'assets/logos/mathiblitz.png',url:'https://www.mathiblitz.ch/',alt:'Mathiblitz'},'Glove Tec GmbH':{logo:'assets/logos/Dogger.jpg',url:'https://www.dogger.ch/',alt:'Dogger / Glove Tec GmbH'},'Luginbühl Tiernahrung GmbH':{logo:'assets/logos/HappyDog.png',url:'https://www.luginbuehl-tiernahrung.ch/',alt:'Happy Dog / Luginbühl Tiernahrung'},'IGKO':{logo:'assets/logos/Logo IGKO.jpg',url:'https://igko.ch/',alt:'IGKO'}};gold.querySelectorAll('.sponsor').forEach(card=>{const h=card.querySelector('h3');if(!h)return;const item=logos[h.textContent.trim()];if(!item||card.querySelector('.gold-card-logo'))return;const box=document.createElement('a');box.className='gold-card-logo';box.href=item.url;box.target='_blank';box.rel='noopener';box.title=item.alt;box.style.cssText='height:130px;display:flex;align-items:center;justify-content:center;margin:-4px 0 22px;text-decoration:none;background:#fff;border:1px solid #eadfc9;padding:16px;';box.innerHTML=`<img src="${siteUrl(item.logo)}" alt="${item.alt}" style="display:block;max-width:88%;max-height:100px;object-fit:contain">`;card.insertBefore(box,h)})}
function siteFooter(){return `${sponsorBlock()}<footer class="site-footer"><div class="site-wrap"><div class="site-footer-grid"><div class="footer-identity"><img class="site-footer-logo" src="${siteUrl('assets/logos/boxerkopf-bern.png')}" alt="Boxer-Club Bern"><div><strong>Boxer-Club Bern</strong><br><span>Ortsgruppe des Schweizerischen Boxer-Clubs</span><br><span>Übungsplatz Struchismoos · Uettligen</span><br><a class="footer-mail" href="mailto:info@boxerclub-bern.ch">info@boxerclub-bern.ch</a></div></div><div><div class="footer-title">Schnellzugriff</div><div class="footer-links"><a href="${siteUrl('club/')}">Club</a><a href="${siteUrl('training/')}">Training</a><a href="${siteUrl('agenda/')}">Agenda</a><a href="${siteUrl('news/')}">News</a><a href="${siteUrl('sponsoren/')}">Sponsoren & Partner</a><a href="${siteUrl('links/')}">Links</a><a href="${siteUrl('mitgliedschaft/')}">Mitgliedschaft</a><a href="${siteUrl('kontakt/')}">Kontakt</a></div></div><div><div class="footer-title">Organisationen</div><div class="footer-org-logos"><a href="https://www.boxerhunde.ch/" target="_blank" rel="noopener"><img src="${siteUrl('assets/logos/sbc.png')}" alt="Schweizerischer Boxer-Club SBC"></a><a href="https://www.skg.ch/" target="_blank" rel="noopener"><img src="${siteUrl('assets/logos/skg.png')}" alt="Schweizerische Kynologische Gesellschaft SKG"></a></div><p class="footer-org"><a href="https://www.boxerhunde.ch/" target="_blank" rel="noopener">Schweizerischer Boxer-Club SBC</a><br><a href="https://www.skg.ch/" target="_blank" rel="noopener">Schweizerische Kynologische Gesellschaft SKG</a></p></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Boxer-Club Bern</span><div><a href="${siteUrl('impressum/')}">Impressum</a><a href="${siteUrl('datenschutz/')}">Datenschutz</a><a href="https://www.facebook.com/boxerclubbern" target="_blank" rel="noopener">Facebook</a></div></div></div></footer>`}
function injectSite(){migrateLegacyAssets();if(!document.querySelector('.top-sponsor-strip'))document.body.insertAdjacentHTML('afterbegin',mainSponsorStrip());const h=document.querySelector('[data-site-header]');if(h)h.innerHTML=siteHeader();else{const old=document.querySelector('header.nav');if(old)old.outerHTML=siteHeader()}const f=document.querySelector('[data-site-footer]');if(f)f.innerHTML=siteFooter();else{const old=document.querySelector('footer');if(old)old.outerHTML=siteFooter()}prettyLinks();enhanceSponsorPage()}
document.addEventListener('DOMContentLoaded',injectSite);